add the news and blog section
Open-Science-Community-Saudi-Arabia/OSCSA_Website pull request #11
Opened 2022-08-09 16:26 UTC by AsmaKacem1

fix: #1 #2 to add a section for the blog and news inside the website
this blog was connected to the quarto blog

2022-08-31 15:45 UTC, BatoolMM requested changes

2022-10-06 07:39 UTC, BatoolMM commented
Hi @AsmaKacem1, I would like to merge this PR but there are 104 files has changed, can you briefly describe what you did and why 104 files were modified, please?

2022-10-10 08:15 UTC, BatoolMM commented
Thank you @AsmaKacem1 for your speedy reply!

I'm still not sure why 105 files have been modified, I'd like to merge this but we can't merge if we don't know why 105 files have changed.

Can you possibly try the following:
- Fork the project (if you already have a fork, remove it and fork again)
- Clone it locally
- Only add replace/add the files you have changed
- Commit the changes and open a new PR

We have a few people working on the website and I don't want your amazing work to go to waste. Thank you again!

2022-10-10 08:27 UTC, AsmaKacem1 commented
Yes of course,I will fix it and follow the steps you mentioned

On Mon, Oct 10, 2022 at 9:15 AM Batool Almarzouq ***@***.***>
wrote:

> Thank you @AsmaKacem1 <https://github.com/AsmaKacem1> for your speedy
> reply!
>
> I'm still not sure why 105 files have been modified, I'd like to merge
> this but we can't merge if we don't know why 105 files have changed.
>
> Can you possibly try the following:
>
>    - Fork the project (if you already have a fork, remove it and fork
>    again)
>    - Clone it locally
>    - Only add replace/add the files you have changed
>    - Commit the changes and open a new PR
>
> We have a few people working on the website and I don't want your amazing
> work to go to waste. Thank you again!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/11#issuecomment-1272942999>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARNOT2DLMNUJRS5HUJ4KKALWCPGDLANCNFSM56BNCBSA>
> .
> You are receiving this because you were mentioned.Message ID:
> <Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/11/c1272942999@
> github.com>
>

2022-10-10 10:00 UTC, closed without merging