[18/10/2022]Task3.2: Added event cards
Open-Science-Community-Saudi-Arabia/OSCSA_Website pull request #187
Opened 2022-10-18 01:10 UTC by sandygudie

### Summary: https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/issues/186
**Tasks 3**
We need to add an events subpage where we can link our events in [Zenodo](https://zenodo.org/communities/1231231664/?page=1&size=20).
3.1 Add this to the nav bar [PR](https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/180).
3.2 Add three cards with each event, title, name of the speaker, and language.

### Fixes <NUM>
* Added event cards on the homepage*
* Users can see listed events when they click the `Event` link on the navbar
* The Arabic version of the page is updated 
Result
![image](https://user-images.githubusercontent.com/54219127/196311283-1bf6d378-ea55-464c-b95a-9014187962df.png)

### What should a reviewer concentrate their feedback on?
- [ ] Everything looks ok?

2022-10-18 01:14 UTC, sandygudie commented
@alswajiab @BatoolMM  please review

2022-10-18 11:39 UTC, BatoolMM commented
This looks fantastic 🌷

Can you make the link for (More OSCSA events) open a new page on the website with all previous events?

2022-10-18 14:04 UTC, sandygudie commented
> This looks fantastic 🌷
> 
> Can you make the link for (More OSCSA events) open a new page on the website with all previous events?

Noted @BatoolMM

2022-10-24 00:53 UTC, BatoolMM commented
It looks fantastic, can you move this section to just before the UNESCO recommendation and resolve the conflict, please?

2022-10-25 19:26 UTC, BatoolMM commented
@sandygudie can you rebase this PR, please?

2022-10-25 19:34 UTC, BatoolMM requested changes

2022-10-25 19:34 UTC, BatoolMM commented on index.html
> +        <h3 class="section-title">Events</h3>
```suggestion
        <h3 class="section-title">Materials and Talks</h3>
        <p class="subscribe-text">All our talks, workshops, and training courses by Community lead and OSCSA members in all events and conferences, including 
         <a "https://elifesciences.org ">eLife</a>
          <a href="https://www.unesco.org/en">UNESCO</a>. 
        are under CC-BY license and accessible in
               <a href="https://zenodo.org/communities/1231231664/?page=1&size=20">Zenodo</a>. 
               Any code associated with these materials is included in our <a href="https://github.com/Open-Science-Community-Saudi-Arabia">GitHub
              Organization Account</a>!</p>
```

2022-10-25 19:34 UTC, BatoolMM commented on index.html
> +        <h6><a  class="font-weight-bold more-event" style="font-size:18px" href="https://zenodo.org/communities/1231231664/?page=1&size=20">  More OSCSA Events</a></h6>
```suggestion
        <h7><a  class="font-weight-bold more-event" style="font-size:18px" href="https://zenodo.org/communities/1231231664/?page=1&size=20">  More OSCSA Materails</a></h7>
```

2022-10-25 19:46 UTC, sandygudie commented
> @sandygudie can you rebase this PR, please?

done @BatoolMM

2022-10-25 19:49 UTC, sandygudie commented
@BatoolMM 
TypoError , "Materials"
![image](https://user-images.githubusercontent.com/54219127/197868033-60382a2d-4e1e-4ac6-96f9-734650f95246.png)

2022-10-25 19:54 UTC, BatoolMM requested changes

2022-10-25 19:54 UTC, BatoolMM commented on ar-index.html
> +      <h3 class="section-title">الأحداث</h3>
```suggestion
      <h3 class="section-title">نشاطاتنا التعليمية</h3>
            <p class="subscribe-text">جميع مشاركتنا، وورشنا العلمية ودوراتنا التدريبية تحت ترخيص CC-BY و
              متاحة في <a href="https://zenodo.org/communities/1231231664/?page=1&size=20">زينودو (Zenodo)</a>. أي كود مرتبط بهذه المواد مضمن في حسابنا على مؤسسة <a href="https://github.com/Open-Science-Community-Saudi-Arabia">GitHub</a> <a href="https://github.com/Open-Science-Community-Saudi-Arabia"></a>.</p>
          </div>

```

2022-10-25 19:54 UTC, BatoolMM commented on ar-index.html
> +            <h6 class="card-title">الاستفادة من العلوم المفتوحة في التعلم الآلي والمعلوماتية الحيوية</h5>
```suggestion
            <h6 class="card-title">الاستفادة من العلوم المفتوحة في الذكاء الإصناعي والمعلوماتية الحيوية</h5>

```

2022-10-25 19:54 UTC, BatoolMM commented on ar-index.html
> +            <p class="card-text">مكبر الصوت: Batool Almarzouq</p>
```suggestion
            <p class="card-text">د.بتول المرزوق</p>

```

2022-10-25 19:54 UTC, BatoolMM commented on ar-index.html
> +            <h6 class="card-title">نحو العولمة الأوسع للمصدر المفتوح: توثيق رحلة الأقلمة الخاصة بك</h5>
```suggestion
            <h6 class="card-title">نحو عولمة أوسع للمصادر المفتوحة: توثيق رحلة التوطين والترجمة</h5>

```

2022-10-25 19:54 UTC, BatoolMM commented on ar-index.html
> +            <p class="card-text">مكبر الصوت: Melissa Black and Asma Kacem</p>
```suggestion
            <p class="card-text">اسماء قاسم ومليسا بلاك</p>

```

2022-10-25 19:54 UTC, BatoolMM commented on ar-index.html
> +            <p class="card-text">مكبر الصوت: Batool Almarzouq</p>
```suggestion
            <p class="card-text">د.بتول المرزوق</p>

```

2022-10-25 19:54 UTC, BatoolMM commented on ar-index.html
> +            <h6 class="card-title">تبسيط سطر الأوامر (عربي)</h5>
```suggestion
            <h6 class="card-title">تبسيط لوحة الأوامر السوداء</h5>

```

2022-10-25 19:57 UTC, BatoolMM commented
> @BatoolMM TypoError , "Materials" ![image](https://user-images.githubusercontent.com/54219127/197868033-60382a2d-4e1e-4ac6-96f9-734650f95246.png) and the divider should be below the title text ![image](https://user-images.githubusercontent.com/54219127/197869150-398988f8-53fc-4ffe-b40c-bf3c10cb771a.png)

Thank you for catching this!

2022-10-25 20:00 UTC, BatoolMM requested changes

2022-10-25 20:00 UTC, BatoolMM commented on index.html
> +        <h3 class="section-title">Materials and Talks</h3>
```suggestion
        <h3 class="section-title"> Materials and Talks</h3>
```

2022-10-25 20:00 UTC, BatoolMM commented on index.html
> +        <h7><a  class="font-weight-bold more-event" style="font-size:18px" href="https://zenodo.org/communities/1231231664/?page=1&size=20">  More OSCSA Materails</a></h7>
```suggestion
        <h7><a  class="font-weight-bold more-event" style="font-size:18px" href="https://zenodo.org/communities/1231231664/?page=1&size=20">  More OSCSA Materials and Talks </a></h7>
```

2022-10-25 20:00 UTC, sandygudie commented
> > @BatoolMM TypoError , "Materials" ![image](https://user-images.githubusercontent.com/54219127/197868033-60382a2d-4e1e-4ac6-96f9-734650f95246.png) and the divider should be below the title text ![image](https://user-images.githubusercontent.com/54219127/197869150-398988f8-53fc-4ffe-b40c-bf3c10cb771a.png)
> 
> Thank you for catching this!

i have fixed this

2022-10-25 20:01 UTC, BatoolMM commented
I made changes to the Arabic translation - The Materials in the nav bar should direct to the cards you created, can you fix that @sandygudie.

2022-10-25 20:02 UTC, sandygudie commented
> I made changes to the Arabic translation - The Materials in the nav bar should direct to the cards you created, can you fix that @sandygudie.

Alright, I will fix that right away

2022-10-25 20:38 UTC, BatoolMM commented
Thank you @sandygudie 🌷 , for the speedy fix, I noticed that the Arabic page has no padding in all directions - the card reaches the end of the screen.

<img width="1421" alt="Screenshot 2022-10-25 at 22 35 12" src="https://user-images.githubusercontent.com/53487593/197876556-be0ef014-0722-45d5-b382-da695b9fd73c.png">

In terms of the English page, needs padding on the top and bottom only.

<img width="1387" alt="Screenshot 2022-10-25 at 22 35 43" src="https://user-images.githubusercontent.com/53487593/197876636-9cdb8d7d-096b-474a-9eb7-37b4fed7e639.png">

Can you fix this issue, I'd love to merge this today but no rush!

2022-10-25 21:01 UTC, sandygudie commented
> Thank you @sandygudie 🌷 , for the speedy fix, I noticed that the Arabic page has no padding in all directions - the card reaches the end of the screen.
> 
> <img alt="Screenshot 2022-10-25 at 22 35 12" width="1421" src="https://user-images.githubusercontent.com/53487593/197876556-be0ef014-0722-45d5-b382-da695b9fd73c.png">
> 
> In terms of the English page, needs padding on the top and bottom only.
> 
> <img alt="Screenshot 2022-10-25 at 22 35 43" width="1387" src="https://user-images.githubusercontent.com/53487593/197876636-9cdb8d7d-096b-474a-9eb7-37b4fed7e639.png">
> 
> Can you fix this issue, I'd love to merge this today but no rush!

I will fix that now

2022-10-25 21:48 UTC, BatoolMM commented
Fantastic! 
Isn't the card supposed to direct you to its page in Zenodo once it's clicked but that's not the case?

2022-10-25 22:31 UTC, sandygudie commented
> Fantastic @sandygudie !
> Isn't the card supposed to direct you to its page in Zenodo once it's clicked but that's not the case?

Based on the Task description(Task 3) clicking on a card should open a more detailed subpage  with description ,  to view slides or download etc

https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/issues/186

2022-10-25 22:55 UTC, BatoolMM commented
@sandygudie It would be nice for each card would direct you to a subpage - but this can be made in a separate PR - otherwise, this will be heavy PR. To merge this PR, it should at least direct you to the slides from Zenodo (their page in Zenodo), if that makes sense! Let me know if that's not clear!

2022-10-26 02:19 UTC, RealRichi3 commented
@sandygudie if you need assistance with the subpages, i'm open to assist

2022-10-26 05:51 UTC, sandygudie commented
> 

Yes, that’s right @BatoolMM,

The subpage is been worked on here https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/191

2022-10-26 06:17 UTC, BatoolMM approved these changes

2022-10-26 06:18 UTC, BatoolMM commented
Looks fantastic, thank you again @sandygudie!

2022-10-26 06:18 UTC, merged

2022-10-26 06:21 UTC, BatoolMM commented
@sandygudie, the CSS for the Arabic page is completely distorted - can you open a PR to fix it, please?

<img width="1398" alt="Screenshot 2022-10-26 at 08 20 24" src="https://user-images.githubusercontent.com/53487593/197949753-b91584c9-45ad-4329-8cba-eab1773d53fe.png">

2022-10-26 06:22 UTC, sandygudie commented
Oh No, i had  just pushed a fixed  before you merged, I will fix it quick
thanks

2022-10-26 06:27 UTC, sandygudie commented
@BatoolMM the fix : https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/214